# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170714_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(default='blog', max_length=32, verbose_name='博客主题'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(upload_to='static/image/', verbose_name='头像'),
        ),
    ]
