# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170720_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128, verbose_name='开通博客理由')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '拒绝'), (2, '已开通')], default=0, verbose_name='申请状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'GoLang'), (4, 'Django')], default=None, verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/static/image/default.jpg', upload_to='static/image/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='申请用户'),
        ),
    ]
