# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170830_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erweima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.CharField(max_length=32, verbose_name='二维码唯一标识')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='状态')),
                ('ctime', models.IntegerField(default=100, verbose_name='超时时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erweima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Erweima', verbose_name='二维码')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='static/image/default.jpg', upload_to='static/image/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='扫码用户'),
        ),
    ]
